import assert from "node:assert/strict";
import { renameSync, mkdirSync, mkdtempSync, realpathSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { validateRecoveryCanonicalDatabaseV01 } from "./recovery-canonical-record-validator";
import { applyCanonicalDatabaseMigrations } from "./canonical-database-migrations.mjs";
import { getOrCreateCanonicalProjectForLocalRootV01, getOrCreateDefaultWorkspaceIdentityV01, normalizeLocalProjectRootRefV01 } from "../lib/vnext/persistence/project-identity-registry";
import { readActiveProjectSelectionV01, selectActiveProjectV01 } from "../lib/vnext/persistence/project-lifecycle-registry";
import { readVNextLocalOperatorCredentialFromRequestV01, VNEXT_LOCAL_OPERATOR_SESSION_COOKIE_V01, consumeVNextLocalOperatorBootstrapV01, issueVNextLocalOperatorBootstrapV01 } from "../lib/vnext/runtime/local-operator-session";
import { defineInitialProjectWorkV01, readProjectWorkInitializationV01 } from "../lib/vnext/runtime/project-work-initialization";
import { buildSelectedWorkSourceEntry, compareSelectedWorkSources, readSelectedWorkSources } from "../lib/intake/selected-work-source-comparison";
import { readCodexProjectContinuityV01 } from "../lib/vnext/codex-current-continuity/codex-current-continuity";
import { initializeCodexRepositoryWorkV01, reviseCodexRepositoryWorkV01 } from "../lib/vnext/codex-repository-continuity/codex-repository-work-revision";
import { revisePreExecutionProjectWorkV01, previewNewProjectWorkV01 } from "../lib/vnext/runtime/project-work-revision";
void main().catch(error => { console.error(error); process.exitCode = 1; });
async function main() {
const root = realpathSync(mkdtempSync(path.join(tmpdir(), "augnes-project-writers-")));
const db = new Database(":memory:");
let tick = 0;
const clock = () => ({ now: () => new Date(Date.parse("2026-08-01T00:00:00Z") + tick++ * 1000).toISOString() });
try {
  applyCanonicalDatabaseMigrations(db);
  const workspace_id = getOrCreateDefaultWorkspaceIdentityV01(db).workspace_id;
  const client = (name: string) => {
    const localRoot = path.join(root, name); mkdirSync(localRoot);
    const project_id = getOrCreateCanonicalProjectForLocalRootV01(db, { workspace_id, local_root: normalizeLocalProjectRootRefV01(localRoot, { base_path: root }), display_name: name }).project.project_id;
    const config = { enabled: true as const, workspace_id, project_id, operator_id: `operator:${name}`, database_path: ":memory:" };
    const issue = issueVNextLocalOperatorBootstrapV01(db, { config, clock: clock() });
    const credential = consumeVNextLocalOperatorBootstrapV01(db, { config, bootstrap_token: issue.bootstrap_token, clock: clock() }).credential;
    return { config, credential, localRoot };
  };
  const a = client("A"), b = client("B");
  const select = (project_id: string) => { const old = readActiveProjectSelectionV01(db, workspace_id); selectActiveProjectV01(db, { workspace_id, project_id, expected_project_id: old?.project_id ?? null, expected_revision: old?.selection_revision ?? null, now: clock().now() }); };
  const definition = { goal: "A unfinished edit", success_criteria: ["Saved in A"], non_goals: [] };
  const initialBinding = readProjectWorkInitializationV01(db, a.config).project_work_binding!;
  const initialRequest = { action: "define_initial_project_work", workspace_id, project_id: a.config.project_id, expected_active_project_id: a.config.project_id, expected_active_selection_revision: readActiveProjectSelectionV01(db, workspace_id)?.selection_revision ?? null, expected_initialization_state: "not_defined", ...definition };
  assert.equal(readActiveProjectSelectionV01(db, workspace_id), null);
  const initial = defineInitialProjectWorkV01(db, { ...a, request: { ...initialRequest, expected_project_work_binding: initialBinding }, clock: clock() });
  select(a.config.project_id);
  a.credential = readVNextLocalOperatorCredentialFromRequestV01(new Request("http://localhost/", { headers: { cookie: `${VNEXT_LOCAL_OPERATOR_SESSION_COOKIE_V01}=${initial.session_admission.cookie_value}` } }));
  const request = { action: "revise_pre_execution_project_work", workspace_id, project_id: a.config.project_id, expected_active_project_id: a.config.project_id, expected_active_selection_revision: readActiveProjectSelectionV01(db, workspace_id)!.selection_revision, expected_current_packet_id: initial.packet.packet_id, expected_current_packet_fingerprint: initial.packet.integrity.fingerprint, expected_current_lineage_kind: "initial_user_defined", ...definition, goal: "A entered text retained" };
  select(b.config.project_id); select(a.config.project_id);
  assert.throws(() => revisePreExecutionProjectWorkV01(db, { ...a, request, clock: clock() }), /work_revision_active_selection_conflict/);
  assert.equal(readProjectWorkInitializationV01(db, a.config).current_work?.goal, definition.goal);
  console.log("Legacy control: exact A edit refused after unrelated A-B-A selection; A packet unchanged");
  const sources = [buildSelectedWorkSourceEntry(a.config, { source: "A note", text: "A unsaved source text", observed_at: null, provenance: "user_declaration", label: "Open question" })];
  const bound = { ...request, expected_project_work_binding: initialBinding, selected_source_context: sources, expected_source_comparison: compareSelectedWorkSources(initial.packet, sources).fingerprint };
  const channel = { key: "disposable-project-work-test-channel", instance_id: "test-instance", generation_id: "test-generation", repository_fingerprint: "sha256:"+"a".repeat(64) };
  const deps = { now: () => clock().now(), managed_start_available: () => false, read_operator_config: () => null };
  const snapshot = async (c: typeof a) => (await readCodexProjectContinuityV01(db, { project_id: c.config.project_id }, deps)).snapshot.binding!;
  const bInitialInput = { intent: "initial_work", action: "preview", repository_root: b.localRoot, expected_snapshot_binding: await snapshot(b), changes: { goal: "B first independent work", success_criteria: ["B readback"], non_goals: [] } };
  const bPreview = await initializeCodexRepositoryWorkV01(db, bInitialInput, channel, deps);
  select(b.config.project_id);
  const revised = revisePreExecutionProjectWorkV01(db, { ...a, request: bound, clock: clock() });
  a.credential = readVNextLocalOperatorCredentialFromRequestV01(new Request("http://localhost/", { headers: { cookie: `${VNEXT_LOCAL_OPERATOR_SESSION_COOKIE_V01}=${revised.session_admission.cookie_value}` } }));
  assert.equal(revised.packet.task.goal, "A entered text retained");
  assert.deepEqual(readSelectedWorkSources(revised.packet), sources);
  select(a.config.project_id);
  assert.equal(await snapshot(b), bInitialInput.expected_snapshot_binding);
  const bInitial = await initializeCodexRepositoryWorkV01(db, { ...bInitialInput, action: "save", preview_binding: bPreview.preview_binding }, channel, deps);
  assert.equal(bInitial.status, "saved");
  await assert.rejects(initializeCodexRepositoryWorkV01(db, { ...bInitialInput, action: "save", preview_binding: bPreview.preview_binding }, channel, deps), /refresh_required/);
  assert.throws(() => revisePreExecutionProjectWorkV01(db, { ...a, request: { ...bound, goal: "Losing overlapping edit" }, clock: clock() }), /work_revision_current_packet_changed/);
  const replay = revisePreExecutionProjectWorkV01(db, { ...a, request: bound, clock: clock() });
  assert.equal(replay.status, "exact_replay");
  a.credential = readVNextLocalOperatorCredentialFromRequestV01(new Request("http://localhost/", { headers: { cookie: `${VNEXT_LOCAL_OPERATOR_SESSION_COOKIE_V01}=${replay.session_admission.cookie_value}` } }));
  const bRevision = { action: "preview", repository_root: b.localRoot, expected_snapshot_binding: await snapshot(b), changes: { goal: "B revised through Companion", sources: { add: [{ source: "B source", text: "B selected material", observed_at: null, provenance: "imported_unverified", label: "Open question" }] } } };
  const bRevisionPreview = await reviseCodexRepositoryWorkV01(db, bRevision, channel, deps);
  select(b.config.project_id); select(a.config.project_id);
  assert.equal(await snapshot(b), bRevision.expected_snapshot_binding);
  const bRevisionSaved = await reviseCodexRepositoryWorkV01(db, { ...bRevision, action: "save", preview_binding: bRevisionPreview.preview_binding }, channel, deps);
  assert.equal(bRevisionSaved.status, "saved");
  select(b.config.project_id);
  assert.equal((await reviseCodexRepositoryWorkV01(db, { ...bRevision, action: "save", preview_binding: bRevisionPreview.preview_binding }, channel, deps)).status, "exact_replay");
  const bNewTask = { intent: "new_task", action: "preview", repository_root: b.localRoot, expected_snapshot_binding: await snapshot(b), changes: { goal: "B explicitly different task", success_criteria: ["Saved only in B"], non_goals: [], sources: { keep: readProjectWorkInitializationV01(db, b.config).selected_source_context!.map(entry => entry.source_ref!), omitted_sources: [] } } };
  const bNewPreview = await reviseCodexRepositoryWorkV01(db, bNewTask, channel, deps);
  const prepareRequest = { ...bound, action: "prepare_new_project_work", goal: "A explicitly different task", expected_current_packet_id: revised.packet.packet_id, expected_current_packet_fingerprint: revised.packet.integrity.fingerprint, expected_current_lineage_kind: "pre_execution_user_revision", expected_source_comparison: compareSelectedWorkSources(revised.packet, sources).fingerprint };
  const preparation = db.transaction(() => previewNewProjectWorkV01(db, a.config, { ...prepareRequest, omitted_sources: [] }))();
  select(a.config.project_id); select(b.config.project_id);
  const prepared = revisePreExecutionProjectWorkV01(db, { ...a, request: preparation.request, clock: clock() });
  assert.equal(prepared.packet.task.goal, "A explicitly different task");
  assert.deepEqual(readSelectedWorkSources(prepared.packet), sources);
  a.credential = readVNextLocalOperatorCredentialFromRequestV01(new Request("http://localhost/", { headers: { cookie: `${VNEXT_LOCAL_OPERATOR_SESSION_COOKIE_V01}=${prepared.session_admission.cookie_value}` } }));
  select(a.config.project_id);
  const bNewSaved = await reviseCodexRepositoryWorkV01(db, { ...bNewTask, action: "save", preview_binding: bNewPreview.preview_binding }, channel, deps);
  assert.equal(bNewSaved.status, "saved");
  const next = { ...bound, goal: "Not saved", expected_current_packet_id: prepared.packet.packet_id, expected_current_packet_fingerprint: prepared.packet.integrity.fingerprint, expected_current_lineage_kind: "pre_execution_new_task", expected_source_comparison: compareSelectedWorkSources(prepared.packet, sources).fingerprint };
  assert.throws(() => revisePreExecutionProjectWorkV01(db, { ...a, request: { ...next, expected_project_work_binding: "sha256:"+"0".repeat(64) }, clock: clock() }), /work_revision_project_binding_changed/);
  assert.throws(() => revisePreExecutionProjectWorkV01(db, { config: a.config, credential: b.credential, request: next, clock: clock() }), /operator_session_scope_mismatch/);
  assert.throws(() => revisePreExecutionProjectWorkV01(db, { ...a, request: { ...next, expected_source_comparison: "sha256:"+"0".repeat(64) }, clock: clock() }), /work_revision_source_comparison_changed/);
  renameSync(a.localRoot, a.localRoot+"-old"); mkdirSync(a.localRoot);
  assert.throws(() => revisePreExecutionProjectWorkV01(db, { ...a, request: next, clock: clock() }), /work_revision_project_binding_changed/);
  rmSync(a.localRoot, { recursive: true }); renameSync(a.localRoot+"-old", a.localRoot);
  const freshA = readProjectWorkInitializationV01(db, a.config), freshB = readProjectWorkInitializationV01(db, b.config);
  assert.equal(freshA.current_work?.goal, "A explicitly different task");
  assert.equal(freshB.current_work?.goal, "B explicitly different task");
  assert.equal(freshB.previous_preparation?.goal, "B revised through Companion");
  assert.equal(freshA.previous_preparation?.goal, "A entered text retained");
  assert.equal(validateRecoveryCanonicalDatabaseV01(db).status, "valid");
  console.log("AFTER: initial Companion preview/save, A edit/source save, exact replay, different-task preparation and B Companion source revision survive controlled selection interleavings; wrong-scope, forged/root-change and overlapping-write refusals retained; fresh A/B readback verified");
} finally { db.close(); rmSync(root, { recursive: true, force: true }); }

}
